# NetlfiyCMS configuration
# https://www.netlifycms.org/docs/configuration-options/#configuration-file
backend:
  name: git-gateway

media_folder: public/img
public_folder: /img

collections:
  - name: 'paintings'
    label: 'Bilder'
    label_singular: 'Bild'
    folder: 'content/_paintings'
    format: 'json'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Name', name: 'title', widget: 'string' }
      - { label: 'Entstehungsjahr', name: 'date', widget: 'datetime', date_format: 'YYYY', time_format: '' }
      - { label: 'Beschreibung', name: 'description', widget: 'string', required: false }
      - { label: 'Technik', name: 'technique', widget: 'string' }
      - { label: 'Maße', name: 'dimensions', widget: 'string', pattern: ['\d+ x \d+', 'Muss dem Format "<Breite> x <Höhe>" folgen'] }
      - { label: 'Bild', name: 'image', widget: 'image' }
  - name: 'rubriken'
    label: 'Rubrik'
    folder: 'content'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Titel', name: 'title', widget: 'string' }
      - { label: 'Banner', name: 'bannerImage', widget: 'image', required: false }
      - { label: 'Inhalt', name: 'body', widget: 'markdown' }
